scoreboard objectives add heart dummy Hearts
scoreboard players add @a heart 0

tag @a remove heart1
tag @a remove heart2
tag @a remove heart3
tag @a remove heart4
tag @a remove heart5
tag @a remove heart6
tag @a remove heart7
tag @a remove heart8
tag @a remove heart9
tag @a remove heart10
tag @a remove heart11
tag @a remove heart12
tag @a remove heart13
tag @a remove heart14
tag @a remove heart15
tag @a remove heart16
tag @a remove heart17
tag @a remove heart18
tag @a remove heart19
tag @a remove heart20
tag @a remove heart21
tag @a remove heart22
tag @a remove heart23
tag @a remove heart24
tag @a remove heart25
tag @a remove heart26
tag @a remove heart27
tag @a remove heart28
tag @a remove heart29
tag @a remove heart30
tag @a remove heart31
tag @a remove heart32
tag @a remove heart33
tag @a remove heart34
tag @a remove heart35
tag @a remove heart36
tag @a remove heart37
tag @a remove heart38
tag @a remove heart39
tag @a remove heart40
tag @a remove heart41
tag @a remove heart42
tag @a remove heart43
tag @a remove heart44
tag @a remove heart45
tag @a remove heart46
tag @a remove heart47
tag @a remove heart48
tag @a remove heart49
tag @a remove heart50
tag @a remove heart51

tag @a[scores={heart=0}] add heart20
tag @a[scores={heart=1}] add heart1
tag @a[scores={heart=2}] add heart2
tag @a[scores={heart=3}] add heart3
tag @a[scores={heart=4}] add heart4
tag @a[scores={heart=5}] add heart5
tag @a[scores={heart=6}] add heart6
tag @a[scores={heart=7}] add heart7
tag @a[scores={heart=8}] add heart8
tag @a[scores={heart=9}] add heart9
tag @a[scores={heart=10}] add heart10
tag @a[scores={heart=11}] add heart11
tag @a[scores={heart=12}] add heart12
tag @a[scores={heart=13}] add heart13
tag @a[scores={heart=14}] add heart14
tag @a[scores={heart=15}] add heart15
tag @a[scores={heart=16}] add heart16
tag @a[scores={heart=17}] add heart17
tag @a[scores={heart=18}] add heart18
tag @a[scores={heart=19}] add heart19
tag @a[scores={heart=20}] add heart20
tag @a[scores={heart=21}] add heart21
tag @a[scores={heart=22}] add heart22
tag @a[scores={heart=23}] add heart23
tag @a[scores={heart=24}] add heart24
tag @a[scores={heart=25}] add heart25
tag @a[scores={heart=26}] add heart26
tag @a[scores={heart=27}] add heart27
tag @a[scores={heart=28}] add heart28
tag @a[scores={heart=29}] add heart29
tag @a[scores={heart=30}] add heart30
tag @a[scores={heart=31}] add heart31
tag @a[scores={heart=32}] add heart32
tag @a[scores={heart=33}] add heart33
tag @a[scores={heart=34}] add heart34
tag @a[scores={heart=35}] add heart35
tag @a[scores={heart=36}] add heart36
tag @a[scores={heart=37}] add heart37
tag @a[scores={heart=38}] add heart38
tag @a[scores={heart=39}] add heart39
tag @a[scores={heart=40}] add heart40
tag @a[scores={heart=41}] add heart41
tag @a[scores={heart=42}] add heart42
tag @a[scores={heart=43}] add heart43
tag @a[scores={heart=44}] add heart44
tag @a[scores={heart=45}] add heart45
tag @a[scores={heart=46}] add heart46
tag @a[scores={heart=47}] add heart47
tag @a[scores={heart=48}] add heart48
tag @a[scores={heart=49}] add heart49
tag @a[scores={heart=50}] add heart50