scoreboard objectives add heart dummy

event entity @a [scores={heart=1}] health1
event entity @a [scores={heart=2}] health2
event entity @a [scores={heart=3}] health3
event entity @a [scores={heart=4}] health4
event entity @a [scores={heart=5}] health5
event entity @a [scores={heart=6}] health6
event entity @a [scores={heart=7}] health7
event entity @a [scores={heart=8}] health8
event entity @a [scores={heart=9}] health9
event entity @a [scores={heart=10}] health10
event entity @a [scores={heart=11}] health11
event entity @a [scores={heart=12}] health12
event entity @a [scores={heart=13}] health13
event entity @a [scores={heart=14}] health14
event entity @a [scores={heart=15}] health15
event entity @a [scores={heart=16}] health16
event entity @a [scores={heart=17}] health17
event entity @a [scores={heart=18}] health18
event entity @a [scores={heart=19}] health19
event entity @a [scores={heart=20}] health20
event entity @a [scores={heart=21}] health21
event entity @a [scores={heart=22}] health22
event entity @a [scores={heart=23}] health23
event entity @a [scores={heart=24}] health24
event entity @a [scores={heart=25}] health25
event entity @a [scores={heart=26}] health26
event entity @a [scores={heart=27}] health27
event entity @a [scores={heart=28}] health28
event entity @a [scores={heart=29}] health29
event entity @a [scores={heart=30}] health30
event entity @a [scores={heart=31}] health31
event entity @a [scores={heart=32}] health32
event entity @a [scores={heart=33}] health33
event entity @a [scores={heart=34}] health34
event entity @a [scores={heart=35}] health35
event entity @a [scores={heart=36}] health36
event entity @a [scores={heart=37}] health37
event entity @a [scores={heart=38}] health38
event entity @a [scores={heart=39}] health39
event entity @a [scores={heart=40}] health40
